name: Daily Wordle Update

on:
  schedule:
    # This runs at 08:05 UTC (12:05 AM PST)
    - cron: '5 8 * * *'
  workflow_dispatch: # Allows you to run it manually for testing

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        # Added pytz so the script can calculate the date in Pacific Time
        run: pip install requests pytz

      - name: Run update script
        run: python autoupdate.py

      - name: Commit and push changes
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add all_words.json
          git commit -m "Automated daily update of past answers" || exit 0
          git push
